# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :
# Box / OS
VAGRANT_BOX = 'bento/ubuntu-20.04'
# Memorable name for your
VM_NAME = 'vagrant-vm-6'
# Host folder to sync
HOST_PATH = '../../../ansible'
# Where to sync to on Guest — 'vagrant' is the default user name
GUEST_PATH = '/home/ansible'
# # VM Port — uncomment this to use NAT instead of DHCP
# VM_PORT = 8080
Vagrant.configure(2) do |config|
  
  # Vagrant box from Hashicorp
  config.vm.box = VAGRANT_BOX
  
  # Actual machine name
  config.vm.hostname = VM_NAME
  # Set VM name in Virtualbox
  config.vm.provider "virtualbox" do |v|
    v.name = VM_NAME
    v.memory = 2048
  end
  config.vm.network "private_network", type: "dhcp"
  # # Port forwarding — uncomment this to use NAT instead of DHCP
  # config.vm.network "forwarded_port", guest: 80, host: VM_PORT
  # Sync folder
  config.vm.synced_folder HOST_PATH, GUEST_PATH
  # Disable default Vagrant folder, use a unique path per project
  config.vm.synced_folder '.', '/home/vagrant', disabled: true

  config.vm.provision "ansible_local" do |ansible|
    ansible.provisioning_path = '/home/ansible/'
    ansible.playbook = '/home/ansible/docker-pull-run.yml'
  end
end