name: test_on_push
on: push
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r python_app/requirements.txt
      - name: Run tests
        run: coverage run app_python/unittests.py
      - name: Tests report
        run: coverage report